version: '3.8'
services:
  backend:
    image: ghcr.io/smwbalfe/shrillecho-playlist-archive/backend:latest
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      .env.prod
    depends_on:
      - redis

  frontend:
    image: ghcr.io/smwbalfe/shrillecho-playlist-archive/frontend:latest
    expose: 
      - "3000"
    ports: 
      - "3000:3000"
    depends_on:
      - redis 
      - backend
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  watchtower:
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /root/.docker/config.json:/config.json
      command: --interval 15 --cleanup

      environment:
        - WATCHTOWER_DEBUG=true
      restart: unless-stopped

volumes:
  postgres_data: