version: '3.8'
services:
  backend:
    image: backend:latest
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      .env.prod
    depends_on:
      - redis

  frontend:
    image: frontend:latest
    expose: 
      - "3000"
    ports: 
      - "3000:3000"
    depends_on:
      - redis 
      - app
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data: