// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID       int64  `json:"id"`
	ArtistID string `json:"artist_id"`
}

type Scrape struct {
	ID     int64       `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type ScrapeArtist struct {
	ScrapeID int64 `json:"scrape_id"`
	ArtistID int64 `json:"artist_id"`
}

type User struct {
	ID pgtype.UUID `json:"id"`
}
