name: 'Infra Pipeline'

on:
  push:
    paths:
      - 'scraper/**'
  pull_request:
  workflow_dispatch:

env:
  TF_WORKING_DIR: './infra/terraform'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: shrillecho
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_do_token: ${{ secrets.DO_TOKEN }}