name: 'Infra Pipeline'

on:
  push:
    paths:
      - 'scraper/**'
  pull_request:
  workflow_dispatch:

env:
  TF_WORKING_DIR: './infra/terraform'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: shrillecho
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download previous Terraform state
      uses: actions/download-artifact@v4
      continue-on-error: true  
      with:
        name: tf-state
        path: ${{ env.TF_WORKING_DIR }}
    
    - uses: hashicorp/setup-terraform@v3
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
    
    - name: Terraform Plan
      run: terraform plan
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
  
    - name: Upload Terraform state
      if: success()  
      uses: actions/upload-artifact@v4
      with:
        name: tf-state
        path: |
          ${{ env.TF_WORKING_DIR }}/*.tfstate
          ${{ env.TF_WORKING_DIR }}/*.tfstate.backup
        retention-days: 90  